spring:
  application:
    name: config-server # spring.application.name
  cloud:
    config:
      server:
        default-label: services-configs # spring.config.server.default-label
        git:
          uri: https://github.com/Nideevl/Car-Rent-Microservices # spring.config.server.default-label.git.url

# Tells Tomcat to listen for network traffic on port 8888
server:
  port: 8888 # server.port
