spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: server-config
        git:
          uri: https://github.com/Nideevl/Car-Rent-Microservices
server:
  port: 8888